//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtAndYou.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey1Results
    {
        public string Medium { get; set; }
        public string Classification { get; set; }
        public string ImageUrl { get; set; }
        public string Name { get; set; }
        public int ID { get; set; }
    }
}
