//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtAndYou.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtInfoEntities2 : DbContext
    {
        public ArtInfoEntities2()
            : base("name=ArtInfoEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Survey1> Survey1 { get; set; }
        public virtual DbSet<Survey1Results> Survey1Results { get; set; }
        public virtual DbSet<Survey2> Survey2 { get; set; }
        public virtual DbSet<Survey2Results> Survey2Results { get; set; }
        public virtual DbSet<Survey3> Survey3 { get; set; }
        public virtual DbSet<Survey3Results> Survey3Results { get; set; }
    }
}
